models:
  - model: Llama-3-8B
    endpoint_name: inference-component-endpoint
    inference_component: llama-3-8b
    backend: LMI
  - model: Llama-3-70B-Instruct
    endpoint_name: inference-component-endpoint
    inference_component: llama-3-70b-instruct
    backend: LMI
  - model: Phi-3-medium-4k-instruct
    endpoint_name: inference-component-endpoint
    inference_component: phi-3-medium-4k
    backend: LMI
